import React from 'react';
import { ChatMessage as ChatMessageType } from '../types';

interface ChatMessageProps {
  message: ChatMessageType;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.role === 'user';
  const messageClasses = isUser
    ? 'bg-blue-500 text-white self-end rounded-br-none'
    : 'bg-gray-200 text-gray-800 self-start rounded-bl-none';

  return (
    <div className={`flex flex-col max-w-xl mx-2 my-1 p-3 rounded-lg shadow-sm ${messageClasses}`}>
      {message.imageUrl && (
        <div className="mb-2 max-w-full overflow-hidden rounded-md">
          <img
            src={message.imageUrl}
            alt="Generated by AI"
            className="w-full h-auto object-cover"
            aria-label="AI generated image"
          />
        </div>
      )}
      {message.text && (
        <div className="text-sm">
          {message.text}
        </div>
      )}
      <div className={`text-xs mt-1 ${isUser ? 'text-blue-100' : 'text-gray-500'} self-end`}>
        {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
      </div>
    </div>
  );
};

export default ChatMessage;